# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20150116_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventAttendee',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('characterID', models.IntegerField()),
                ('characterName', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('itemID', models.IntegerField()),
                ('locationID', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('singleton', models.IntegerField()),
                ('rawQuantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contactID', models.IntegerField()),
                ('contactName', models.CharField(max_length=100)),
                ('inWatchlist', models.BooleanField()),
                ('standing', models.IntegerField()),
                ('contactType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterContract',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contractID', models.IntegerField()),
                ('issuerID', models.IntegerField()),
                ('issuerCorpID', models.IntegerField()),
                ('assigneeID', models.IntegerField()),
                ('acceptorID', models.IntegerField()),
                ('startStationID', models.IntegerField()),
                ('endStationID', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('forCorp', models.BooleanField()),
                ('availability', models.CharField(max_length=10)),
                ('dateIssued', models.DateTimeField()),
                ('dateExpired', models.DateTimeField()),
                ('dateAccepted', models.DateTimeField()),
                ('numDays', models.IntegerField()),
                ('dateCompleted', models.DateTimeField()),
                ('price', models.FloatField()),
                ('reward', models.FloatField()),
                ('collateral', models.FloatField()),
                ('buyout', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterImplant',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterKill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('killID', models.IntegerField()),
                ('solarSystemID', models.IntegerField()),
                ('killTime', models.DateTimeField()),
                ('victimAllianceID', models.IntegerField()),
                ('victimAllianceName', models.CharField(max_length=100)),
                ('victimCharacterID', models.IntegerField()),
                ('victimCharacterName', models.CharField(max_length=100)),
                ('victimCorporationID', models.IntegerField()),
                ('victimCorporationName', models.CharField(max_length=100)),
                ('victimDamageTaken', models.IntegerField()),
                ('victimShipTypeID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('messageID', models.IntegerField()),
                ('senderID', models.IntegerField()),
                ('sentDate', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('toCorpOrAllianceID', models.CharField(max_length=200)),
                ('toCharacterIDs', models.CharField(max_length=200)),
                ('toListID', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMarketOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('orderID', models.IntegerField()),
                ('charID', models.IntegerField()),
                ('stationID', models.IntegerField()),
                ('volEntered', models.IntegerField()),
                ('volRemaining', models.IntegerField()),
                ('minVolume', models.IntegerField()),
                ('orderState', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('range', models.IntegerField()),
                ('accountKey', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('escrow', models.FloatField()),
                ('price', models.FloatField()),
                ('bid', models.BooleanField()),
                ('issued', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterNotification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notificationID', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('senderID', models.IntegerField()),
                ('sentDate', models.DateTimeField()),
                ('read', models.BooleanField()),
                ('body', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeID', models.IntegerField()),
                ('skillpoints', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterTitle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('titleID', models.IntegerField()),
                ('titleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractItems',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('recordID', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rawQuantity', models.IntegerField()),
                ('singleton', models.BooleanField()),
                ('included', models.BooleanField()),
                ('contract', models.ForeignKey(to='core.CharacterContract')),
            ],
        ),
        migrations.CreateModel(
            name='CorpContact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('contactID', models.IntegerField()),
                ('contactName', models.CharField(max_length=100)),
                ('contactStanding', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorpMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('characterID', models.IntegerField()),
                ('characterName', models.CharField(max_length=100)),
                ('joinDate', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('logonDate', models.DateTimeField()),
                ('logoffDate', models.DateTimeField()),
                ('locationID', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('shipTypeID', models.IntegerField()),
                ('roles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorpStarbase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('itemID', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('locationID', models.IntegerField()),
                ('moonID', models.IntegerField()),
                ('state', models.IntegerField()),
                ('stateTimestamp', models.DateTimeField()),
                ('onlineTimestamp', models.DateTimeField()),
                ('standingOwnerID', models.IntegerField()),
                ('allowCorpMembers', models.BooleanField()),
                ('allowAllianceMembers', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CorpStarbaseFuel',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('typeID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('pos', models.ForeignKey(to='core.CorpStarbase')),
            ],
        ),
        migrations.CreateModel(
            name='KillmailAttackers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('allianceID', models.IntegerField()),
                ('allianceName', models.CharField(max_length=100)),
                ('corporationID', models.IntegerField()),
                ('corporationName', models.CharField(max_length=100)),
                ('characterID', models.IntegerField()),
                ('characterName', models.CharField(max_length=100)),
                ('damageDone', models.IntegerField()),
                ('finalBlow', models.BooleanField()),
                ('shipTypeID', models.IntegerField()),
                ('weaponTypeID', models.IntegerField()),
                ('killmail', models.ForeignKey(to='core.CharacterKill')),
            ],
        ),
        migrations.CreateModel(
            name='KillmailItems',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('flag', models.IntegerField()),
                ('qtyDropped', models.IntegerField()),
                ('qtyDestroyed', models.IntegerField()),
                ('typeID', models.IntegerField()),
                ('singleton', models.IntegerField()),
                ('killmail', models.ForeignKey(to='core.CharacterKill')),
            ],
        ),
        migrations.CreateModel(
            name='WalletJournal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('date', models.DateTimeField()),
                ('refID', models.IntegerField()),
                ('refTypeID', models.IntegerField()),
                ('ownerName1', models.CharField(max_length=100)),
                ('ownerID1', models.IntegerField()),
                ('ownerName2', models.CharField(max_length=100)),
                ('ownerID2', models.IntegerField()),
                ('argName1', models.CharField(max_length=50)),
                ('argID1', models.IntegerField()),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('transactionDateTime', models.DateTimeField()),
                ('transactionID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('typeName', models.CharField(max_length=100)),
                ('typeID', models.IntegerField()),
                ('price', models.IntegerField()),
                ('clientID', models.IntegerField()),
                ('clientName', models.CharField(max_length=100)),
                ('stationID', models.IntegerField()),
                ('stationName', models.CharField(max_length=200)),
                ('transactionType', models.CharField(max_length=5)),
                ('transactionFor', models.CharField(max_length=15)),
                ('journalTransactionID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='accessMask',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='accountCreateDate',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 49, 22, 656000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='accountLogonCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='accountLogonMinutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='accountPaidUntil',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 49, 42, 612000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 49, 48, 991000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='dateOfBirth',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 49, 55, 625000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='jumpActivation',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 50, 8, 338000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='jumpFatigue',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 50, 13, 362000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(default='black', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skillInTrainingFinishes',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 16, 19, 50, 31, 537000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skillInTrainingID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='walletBalance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='walletjournal',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='charactertitle',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='characternotification',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='charactermarketorder',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='charactermail',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='characterkill',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='characterimplant',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='charactercontract',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='charactercontact',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='characterasset',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
        migrations.AddField(
            model_name='calendareventattendee',
            name='owner',
            field=models.ForeignKey(to='core.Character'),
        ),
    ]
