"""
Django settings for baerscore project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xp@qg00%%^n3&d3a%s@6efw^aol!f)&017sqf*un*+qpiof4n&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

TEMPLATE_DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'applications',
    'srp',
    'subreddit',
    'timerboard',
    'hipchat',
    'corpmarket'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'baerscore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.preprocessors.template_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'baerscore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'


# EVE things

# EVE SSO settings
# Get your credentials at https://developers.eveonline.com/ 
SSO_CLIENT_ID = "3d12024f14b8469a80eb342555b53edc"
SSO_SECRET_KEY = "7KOgjRki0ThJNBTrOflnWJDj15xn5jFAllk4tTSs"
SSO_CALLBACK_URL = "http://localhost:8000/evesso"


# Corp ID (easiest way to get this is searching your corp on zKillboard)
CORP_ID = 98224068

# These two do not have to be exactly what they are ingame, they're only used for display
CORP_FULLNAME = "Dropbears Anonymous"
CORP_SHORTNAME = "BAERS"

# full corp API key
CORP_API_KEYID = "01234"
CORP_API_VCODE = "abcdefghijklmnopqrstuvwxyz"

# Same as above, for your alt/logistics corp if you have one
ALTCORP_ID = 98262005
ALTCORP_FULLNAME = "Awox in Progress..."
ALTCORP_SHORTNAME = "AWOX"

ALTCORP_API_KEYID = "12121"
ALTCORP_API_VCODE = "asdddddddddddddddddd"

# ID of home system (zkillboard helps)
HOME_SYSTEM_ID = 31002487


# Reddit

# Enable/Disable reddit functionality
REDDIT_ENABLED = True

# Reddit account that is a moderator on your subreddit
REDDIT_USERNAME = "DropbearsAnonymous"
REDDIT_PASSWORD = "redacted"

# Subreddit name (without the "/r/")
REDDIT_SUBREDDIT = "BAERS"


# Useful links to be displayed in the sidebar
USEFUL_LINKS = [
    ("Subreddit", "http://reddit.com/r/baers"),
    ("Pasta WH Tool", "http://wh.pasta.gg"),
    ("DScan Parser", "https://adashboard.info/intel"),
    ("Siggy", "http://siggy.borkedlabs.com"),
    ("STAHP Tracker", "http://tracker.dropbear.life")
]


# Application Questions
# Provide questions as a list of dictionaries
# "type" can be "short" for a single line answer, or "long" for a multi-line text field
#
# (You can change these without breaking existing apps)

APP_QUESTIONS = [
    {"text": "How old are you?", "type": "short"},
    {"text": "What's your first name?", "type": "short"},
    {"text": "Write a ballad about the rise and fall of the glorious Nova empire, beginning with the events of Clarion Call 3 to the eviction of Dropbears.", "type": "long"},
]



# Corp Market
# 
# You can declare a list of 1 or more CHAs to be the "corp market". These act as a central storage, and you can track the availability of items in them via the corp market tab on the website.
# They will also be used to track fuel blocks on the accounting page
#
# To find the itemIDs of the CHAs, you will have to manually look for them in an API reader.
STORAGE_CHAS = [1014516459082,1014612434725,1014611085566]

# TypeID of the main fuel type you use.
# Minmatar: 4246 -- Amarr: 4247 -- Caldari: 4051 -- Gallente: 4312
FUEL_TYPE = 4247

# Random Haiku widget
#
# We ask all of our applicants to submit a haiku about a DAMN PATRIOT's sexual prowess
# One of these will be displayed on the front page
HAIKU_ENABLED = False


